### ISSUE TITLE
Full working example of preload and ipcHelper with communication

### ISSUE THREAD

**Issue by ADumaine** [alex8088/electron-toolkit#2]
### Clear and concise description of the problem

I have converted an existing application from vue-cli to vite and have tried using electron-vite and toolkit but I am having an issue with the preload and ipcHelper.

I am getting the following error which seems to be from electron loading.

![image](https://user-images.githubusercontent.com/1069218/206265281-0e481548-588d-464c-a6e5-5bda3c7c67db.png)

### Suggested solution

Create a full working with preload and  ipc communication like electron-vite-boilerplate.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@ADumaine `node integration` is not supported, because it is not the best way. So not work like: `import { ipcRenderer } from electron` in renderers. It is recommended to use `preload` to use the node's ability, and the [@electron-toolkit/preload](https://github.com/alex8088/electron-toolkit/tree/master/packages/preload) package is added to improve the development experience. 

If you insist on `node integration`, you need to enable node integration and use the `require` to import the electron or node module, which is not very elegant.

**Comment by ADumaine** [comment]
I did change to using contextIsolation = true and nodeintegration false.   The problem was an import for ipcRenderer I had missed while removing them from components.

I also got it working using window.electron.ipcRenderer.on(......
But it still would be helpful seeing a full example.  :)

Thanks for the quick reply!

**Comment by alex8088** [comment]
@ADumaine Thanks! It is necessary to improve the examples of IPC usage in [boilerplate](https://github.com/alex8088/electron-vite-boilerplate) and electron-vite docs.
